app:
  name: "LINE AI Assistant"
  version: "1.0.0"
  debug: true

server:
  host: '0.0.0.0'
  port: 8000

logging:
  level: "DEBUG"
  format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  file_path: "logs/app.log"
  rotation: "500 MB"
  retention: "10 days"

database:
  url: "postgresql://user:password@localhost:5432/line_ai_db"