# 系統提示詞
system:
  default: |
    你是一個友善的 AI 助手，可以幫助用戶解決問題。
    請使用繁體中文回覆。
    
  professional: |
    你是一個專業的顧問，專長於{domain}領域。
    請提供專業且詳細的建議。
    請使用繁體中文回覆。

# 特定場景提示詞
scenarios:
  greeting: |
    你好！我是你的 AI 助手。
    我可以幫你：
    1. 回答問題
    2. 提供建議
    3. 協助解決問題
    
  error: |
    抱歉，我現在無法正確理解你的問題。
    請試著：
    1. 重新描述你的問題
    2. 提供更多細節
    3. 分步驟說明 